---
# tasks file for jenkins-centos
# https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins+on+Red+Hat+distributions
- name: Install JDK
  yum:
    name: "{{ jenkins_jdk }}"
    update_cache: yes
  when: jenkins_jdk != "no" and jenkins_jdk
- name: Add repository
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
- name: Add jenkins-ci.org.key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
- name: Install jenkins
  yum:
    name: jenkins
    update_cache: yes

- name: set JENKINS_PORT
  lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: "^JENKINS_PORT="
    line: 'JENKINS_PORT="{{jenkins_port}}"'
  when: jenkins_port is defined
- name: set JENKINS_LISTEN_ADDRESS
  lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: "^JENKINS_LISTEN_ADDRESS="
    line: 'JENKINS_LISTEN_ADDRESS="{{jenkins_listen_address}}"'
  when: jenkins_listen_address is defined
- name: set JENKINS_ARGS
  lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: "^JENKINS_ARGS="
    line: 'JENKINS_ARGS="{{jenkins_args}}"'
  when: jenkins_args is defined

- name: Change jenkins state
  service:
    name: jenkins
    state: "{{ jenkins_state }}"
  when: jenkins_state != "no" and jenkins_state
- name: Change whether the service should start on boot
  service:
    name: jenkins
    enabled: "{{ jenkins_enabled }}"
  when: jenkins_enabled != "default"
